[package]
name = "insolencelib"
version = "0.1.0"
edition = "2024"

[lib]
name = "insolencelib"
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.10.5", features = ["lua54", "module"] }
rand = "0.9.1"
