[package]
name = "libinsolence"
version = "0.1.1"
edition = "2024"
build = "build.rs"

[lib]
name = "libinsolence"
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.10.5", features = ["luajit", "module"] }
rand = "0.9.1"
